name: run tests

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install web modules
        run: yarn
        working-directory: web
      - name: Run web tests
        run: yarn test
        working-directory: web
      - name: Install backend gems
        run: bundle
        working-directory: backend
      - name: Run backend tests
        run: bin/rails test
        working-directory: backend
