name: run jest tests

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: web
      - name: Run tests
        run: yarn test
        working-directory: web
